# Generated by Django 4.1.10 on 2023-07-23 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loanapp", "0003_alter_customer_aadhar_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="customer",
        ),
    ]
