# Generated by Django 4.1.10 on 2023-07-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanapp", "0004_remove_customer_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="aadhar_id",
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email_id",
            field=models.EmailField(max_length=254),
        ),
    ]
