# Generated by Django 4.1.10 on 2023-07-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loanapp", "0005_alter_customer_aadhar_id_alter_customer_email_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_transaction_date", models.DateTimeField(blank=True, null=True)),
                ("next_emi_date", models.DateField(blank=True, null=True)),
                (
                    "next_emi_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("initial_emi_amounts", models.CharField(max_length=1000)),
                ("total_emis_left", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="loan",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="LoanDetails",
        ),
        migrations.AddField(
            model_name="loandetail",
            name="loan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan",
                to="loanapp.loan",
            ),
        ),
    ]
