# Generated by Django 4.1.10 on 2023-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanapp", "0006_loandetail_alter_loan_end_date_delete_loandetails_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loandetail",
            old_name="loan_id",
            new_name="loan",
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("car", "car"),
                    ("home", "home"),
                    ("education", "education"),
                    ("personal", "personal"),
                ],
                max_length=25,
            ),
        ),
    ]
