# Generated by Django 4.1.10 on 2023-07-24 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loanapp", "0007_rename_loan_id_loandetail_loan_alter_loan_loan_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="remaining_amount",
        ),
    ]
